### ISSUE TITLE
pop函数返回None

### ISSUE THREAD

**Issue by Downtime111** [Cyberbolt/CyberDB#2]
我在使用 cyberlist 时，发现其pop函数返回None,这是我的部分代码：
```
with client.get_proxy() as proxy:
        operate = proxy.get_cyberlist('operate')
        if operate:
            o_message = operate.pop(0)
```

**Comment by Cyberbolt** [comment]
https://github.com/Cyberbolt/CyberDB#%E6%B3%A8%E6%84%8F
由于编码限制，CyberDB 会将 0 识别为 None，但并不影响计算，请在所需位置将 None 转为 0。
